// <auto-generated />
namespace PizzaTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Queue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Queue));
        
        string IMigrationMetadata.Id
        {
            get { return "201409291931593_Queue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
